# Generated by Django 5.1.2 on 2024-10-21 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('tags', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('lead', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'articles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'keywords',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=400, unique=True)),
                ('scraped', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'links',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArticleKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.article')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.keyword')),
            ],
            options={
                'db_table': 'article_keywords',
                'unique_together': {('article', 'keyword')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(related_name='articles', through='factChecker.ArticleKeyword', to='factChecker.keyword'),
        ),
    ]
