# Generated by Django 5.1.2 on 2024-10-14 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factChecker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('tags', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('lead', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeographicCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('weight', models.IntegerField(help_text='Percentage value associated with this gc')),
            ],
            options={
                'ordering': ['-weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IPTCCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('weight', models.IntegerField(help_text='Percentage value associated with this IPTC code')),
            ],
            options={
                'ordering': ['-weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SABCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleGeographicCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.article')),
                ('geographic_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.geographiccode')),
            ],
            options={
                'unique_together': {('article', 'geographic_code')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='geographic_codes',
            field=models.ManyToManyField(related_name='articles', through='factChecker.ArticleGeographicCode', to='factChecker.geographiccode'),
        ),
        migrations.CreateModel(
            name='ArticleInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.article')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.institution')),
            ],
            options={
                'unique_together': {('article', 'institution')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='institutions',
            field=models.ManyToManyField(related_name='articles', through='factChecker.ArticleInstitution', to='factChecker.institution'),
        ),
        migrations.CreateModel(
            name='ArticleIPTCCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.article')),
                ('iptc_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.iptccode')),
            ],
            options={
                'unique_together': {('article', 'iptc_code')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='iptc_codes',
            field=models.ManyToManyField(related_name='articles', through='factChecker.ArticleIPTCCode', to='factChecker.iptccode'),
        ),
        migrations.CreateModel(
            name='ArticlePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.article')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.person')),
            ],
            options={
                'unique_together': {('article', 'person')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='persons',
            field=models.ManyToManyField(related_name='articles', through='factChecker.ArticlePerson', to='factChecker.person'),
        ),
        migrations.CreateModel(
            name='ArticleSABCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.article')),
                ('sab_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.sabcode')),
            ],
            options={
                'unique_together': {('article', 'sab_code')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='sab_codes',
            field=models.ManyToManyField(related_name='articles', through='factChecker.ArticleSABCode', to='factChecker.sabcode'),
        ),
    ]
