# Generated by Django 5.1.2 on 2024-10-28 20:38

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factChecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024, null=True),
        ),
    ]
