# Generated by Django 5.1.2 on 2024-11-12 20:01

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factChecker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=1024, null=True)),
                ('embedding_openai', pgvector.django.VectorField(dimensions=1536, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.article')),
            ],
            options={
                'db_table': 'chunks',
                'managed': True,
            },
        ),
    ]
