# Generated by Django 5.1.2 on 2024-10-19 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factChecker', '0002_article_geographiccode_institution_iptccode_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('weight', models.IntegerField(help_text='Percentage value associated with this keyword')),
            ],
            options={
                'ordering': ['-weight', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='geographic_codes',
        ),
        migrations.AlterUniqueTogether(
            name='articleinstitution',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='articleinstitution',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleinstitution',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='article',
            name='institutions',
        ),
        migrations.AlterUniqueTogether(
            name='articleiptccode',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='articleiptccode',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleiptccode',
            name='iptc_code',
        ),
        migrations.RemoveField(
            model_name='article',
            name='iptc_codes',
        ),
        migrations.AlterUniqueTogether(
            name='articleperson',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='articleperson',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleperson',
            name='person',
        ),
        migrations.RemoveField(
            model_name='article',
            name='persons',
        ),
        migrations.AlterUniqueTogether(
            name='articlesabcode',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='articlesabcode',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlesabcode',
            name='sab_code',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sab_codes',
        ),
        migrations.CreateModel(
            name='ArticleKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.article')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.keyword')),
            ],
            options={
                'unique_together': {('article', 'keyword')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(related_name='articles', through='factChecker.ArticleKeyword', to='factChecker.keyword'),
        ),
        migrations.DeleteModel(
            name='ArticleGeographicCode',
        ),
        migrations.DeleteModel(
            name='GeographicCode',
        ),
        migrations.DeleteModel(
            name='ArticleInstitution',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='ArticleIPTCCode',
        ),
        migrations.DeleteModel(
            name='IPTCCode',
        ),
        migrations.DeleteModel(
            name='ArticlePerson',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='ArticleSABCode',
        ),
    ]
