# Generated by Django 5.1.2 on 2024-12-22 10:03

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factChecker', '0003_article_embedding_article_embedding_openai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='embedding_openai',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
    ]
