# Generated by Django 5.1.2 on 2025-01-05 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factChecker', '0006_chatsession_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.article')),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_relations', to='factChecker.chatmessage')),
            ],
            options={
                'unique_together': {('chat_message', 'article')},
            },
        ),
    ]
