# Generated by Django 5.1.2 on 2025-01-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factChecker', '0007_chatmessagearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='valuable_info',
            field=models.TextField(null=True),
        ),
    ]
