# Generated by Django 5.1.2 on 2025-01-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factChecker', '0008_chatmessage_valuable_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='valuable_info',
        ),
    ]
