# Generated by Django 5.1.2 on 2025-01-15 12:00

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factChecker', '0011_alter_benchmark_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticChunkEnhanced',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=1024, null=True)),
                ('embedding_openai', pgvector.django.VectorField(dimensions=1024, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.article')),
            ],
            options={
                'db_table': 'enhanced_semantic_chunks',
                'managed': True,
            },
        ),
    ]
