# Generated by Django 5.1.2 on 2025-01-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factChecker', '0012_semanticchunkenhanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanticchunkenhanced',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
