# Generated by Django 5.1.2 on 2025-02-09 19:02

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factChecker', '0013_semanticchunkenhanced_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanticchunk',
            name='embedding_modernbert',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
    ]
