# Generated by Django 5.1.2 on 2025-02-09 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factChecker', '0014_semanticchunk_embedding_modernbert'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphBenchmark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factChecker.article')),
            ],
            options={
                'db_table': 'graph_benchmark',
                'managed': True,
            },
        ),
    ]
